language: go

go:
  - 1.9
  
branches:
  only:
    - master

before_install:
- ./look_for_logs.sh
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/lint/golint
- go get github.com/GeertJohan/fgt
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
  
script:
- fgt golint core
- fgt golint cli
- fgt golint integration_tests
- $HOME/gopath/bin/goveralls -service=travis-ci -ignore core/discoverybase.go,core/discoveryv2.go -package github.com/brotherlogic/discovery/core