// Code generated by protoc-gen-go.
// source: discovery.proto
// DO NOT EDIT!

/*
Package discovery is a generated protocol buffer package.

It is generated from these files:
	discovery.proto

It has these top-level messages:
	RegistryEntry
*/
package discovery

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegistryEntry struct {
	// The ip address associated with this entry
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	// The port number assigned / requested for this entry
	Port int32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	// The name of this service
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// Is this an external facing port
	ExternalPort bool `protobuf:"varint,4,opt,name=external_port,json=externalPort" json:"external_port,omitempty"`
	// This is the machine identifier
	Identifier string `protobuf:"bytes,5,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *RegistryEntry) Reset()                    { *m = RegistryEntry{} }
func (m *RegistryEntry) String() string            { return proto.CompactTextString(m) }
func (*RegistryEntry) ProtoMessage()               {}
func (*RegistryEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*RegistryEntry)(nil), "discovery.RegistryEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for DiscoveryService service

type DiscoveryServiceClient interface {
	RegisterService(ctx context.Context, in *RegistryEntry, opts ...grpc.CallOption) (*RegistryEntry, error)
	Discover(ctx context.Context, in *RegistryEntry, opts ...grpc.CallOption) (*RegistryEntry, error)
}

type discoveryServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryServiceClient(cc *grpc.ClientConn) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) RegisterService(ctx context.Context, in *RegistryEntry, opts ...grpc.CallOption) (*RegistryEntry, error) {
	out := new(RegistryEntry)
	err := grpc.Invoke(ctx, "/discovery.DiscoveryService/RegisterService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) Discover(ctx context.Context, in *RegistryEntry, opts ...grpc.CallOption) (*RegistryEntry, error) {
	out := new(RegistryEntry)
	err := grpc.Invoke(ctx, "/discovery.DiscoveryService/Discover", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DiscoveryService service

type DiscoveryServiceServer interface {
	RegisterService(context.Context, *RegistryEntry) (*RegistryEntry, error)
	Discover(context.Context, *RegistryEntry) (*RegistryEntry, error)
}

func RegisterDiscoveryServiceServer(s *grpc.Server, srv DiscoveryServiceServer) {
	s.RegisterService(&_DiscoveryService_serviceDesc, srv)
}

func _DiscoveryService_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discovery.DiscoveryService/RegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).RegisterService(ctx, req.(*RegistryEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discovery.DiscoveryService/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).Discover(ctx, req.(*RegistryEntry))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscoveryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _DiscoveryService_RegisterService_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _DiscoveryService_Discover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("discovery.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xc9, 0x2c, 0x4e,
	0xce, 0x2f, 0x4b, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0xf5, 0x30, 0x72, 0xf1, 0x06, 0xa5, 0xa6, 0x67, 0x16, 0x97, 0x14, 0x55, 0xba, 0xe6, 0x01, 0x09,
	0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x02, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x20, 0x4b, 0x48,
	0x88, 0x8b, 0xa5, 0x20, 0xbf, 0xa8, 0x44, 0x82, 0x09, 0x28, 0xc2, 0x1a, 0x04, 0x66, 0x83, 0xc4,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc1, 0xaa, 0xc0, 0x6c, 0x21, 0x65, 0x2e, 0xde, 0xd4, 0x8a,
	0x92, 0xd4, 0xa2, 0xbc, 0xc4, 0x9c, 0x78, 0xb0, 0x06, 0x16, 0xa0, 0x24, 0x47, 0x10, 0x0f, 0x4c,
	0x30, 0x00, 0xa4, 0x51, 0x8e, 0x8b, 0x2b, 0x33, 0x25, 0x35, 0xaf, 0x24, 0x33, 0x2d, 0x33, 0xb5,
	0x48, 0x82, 0x15, 0xac, 0x1d, 0x49, 0xc4, 0x68, 0x2e, 0x23, 0x97, 0x80, 0x0b, 0xcc, 0x71, 0xc1,
	0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xee, 0x5c, 0xfc, 0x10, 0x27, 0xa6, 0x16, 0xc1, 0x84,
	0x24, 0xf4, 0x10, 0x7e, 0x42, 0x71, 0xbe, 0x14, 0x4e, 0x19, 0x25, 0x06, 0x21, 0x07, 0x2e, 0x0e,
	0x98, 0xe1, 0xe4, 0x99, 0x90, 0xc4, 0x06, 0x0e, 0x40, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x03, 0x16, 0x8a, 0xa9, 0x53, 0x01, 0x00, 0x00,
}
