name: FindLogs

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]


jobs:
  checks:
    name: basic_assess
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
     
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.1'

    - name: Check for logs
      run: ./look_for_logs.sh